/**
 * Classes generated by the Android Studio master-detail activity wizard, and then modified for
 * the Northwind application.
 *
 * @see com.northwind.nwandroid.NorthwindApp
 */
package com.northwind.view;